name: "DevSecOps: IaC Security Scan"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkov_scan:
    name: Checkov Static Analysis
    runs-on: ubuntu-latest
    
    steps:
      # 1. ดึงโค้ดจาก Repo ลงมาที่เครื่อง Runner บนคลาวด์
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. เรียกใช้งาน Checkov สแกนโฟลเดอร์ terraform ทั้งหมด
      - name: Run Checkov Scan
        uses: bridgecrewio/checkov-action@master
        with:
          directory: terraform/
          framework: terraform
          output_format: cli
          soft_fail: true # ตั้งเป็น true เพื่อให้ Pipeline ผ่านฉลุยก่อน แล้วค่อยมาไล่ดู Report สวยๆ ครับ